FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD mtm-kafka-producer.jar /opt/mtm-kafka-producer/
EXPOSE 8080
WORKDIR /opt/mtm-kafka-producer/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "mtm-kafka-producer.jar"]
